import assetPath from '../utils/assetPath';

function SpectralLearning() {
  return (
    <div>
      <div className="page-header">
        <h1>2D Navier-Stokes Fourier Neural Operator</h1>
        <p>
          A Fourier neural operator trained to approximate finite time evolution for periodic, incompressible
          two-dimensional Navier-Stokes flow in vorticity form.
        </p>
      </div>

      <div className="media-grid three-up">
        <figure className="media-card">
          <video autoPlay muted loop playsInline>
            <source src={assetPath('fno_ns2d_solver.mp4')} type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          <figcaption>Reference pseudospectral RK4 solution.</figcaption>
        </figure>
        <figure className="media-card">
          <video autoPlay muted loop playsInline>
            <source src={assetPath('fno_ns2d_fno.mp4')} type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          <figcaption>Fourier neural operator finite time prediction.</figcaption>
        </figure>
        <figure className="media-card">
          <video autoPlay muted loop playsInline>
            <source src={assetPath('fno_ns2d_absolute_error.mp4')} type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          <figcaption>Absolute pointwise error between the FNO prediction and solver solution.</figcaption>
        </figure>
      </div>

      <section className="writeup-section">
        <h2>Equation</h2>
        <p>
          The model is trained on the two-dimensional incompressible Navier-Stokes equations in periodic vorticity form:
        </p>
        <p className="math-block">{String.raw`\[
          \omega_t + u \cdot \nabla \omega = \nu \Delta \omega,
          \qquad
          u = (\psi_y, -\psi_x),
          \qquad
          -\Delta \psi = \omega.
        \]`}</p>
        <p>
          Here <span>{String.raw`\(\omega(x,y,t)\)`}</span> is vorticity,{' '}
          <span>{String.raw`\(u(x,y,t)\)`}</span> is the incompressible velocity field recovered from a streamfunction,
          and <span>{String.raw`\(\nu\)`}</span> is viscosity. The simulation domain is periodic on{' '}
          <span>{String.raw`\([0, 2\pi)^2\)`}</span>.
        </p>
      </section>

      <section className="writeup-section">
        <h2>Operator Learning Setup</h2>
        <p>
          The learned object is not one particular trajectory, but a finite time solution operator mapping an initial
          vorticity field, spatial coordinates, viscosity, and output time to the corresponding vorticity field:
        </p>
        <p className="math-block">{String.raw`\[
          \mathcal{G}_{\theta}:
          \left(\omega_0(x,y), x, y, \nu, T\right)
          \mapsto
          \omega(x,y,T).
        \]`}</p>
        <p>
          Training data is generated by sampling smooth random initial vorticity fields, adding coherent vortices, drawing
          a viscosity value, and evolving the PDE with a pseudospectral Runge-Kutta solver. The model then learns to
          predict the solver&apos;s final vorticity state.
        </p>
      </section>

      <section className="writeup-section">
        <h2>Fourier Layer</h2>
        <p>
          A Fourier neural operator alternates between local channel mixing in physical space and global convolution in
          frequency space. In two dimensions, a block has the form
        </p>
        <p className="math-block">{String.raw`\[
          v_{k+1}(x,y) =
          \sigma\left(
            W_k v_k(x,y) +
            \mathcal{F}^{-1}
            \left[
              R_k(\xi_1,\xi_2)\,
              \mathcal{F}[v_k](\xi_1,\xi_2)
            \right](x,y)
          \right).
        \]`}</p>
        <p>
          The implementation keeps a fixed number of low Fourier modes in each spatial direction and learns complex
          multipliers on those modes. This gives the network direct access to large scale coherent flow structure while
          keeping the parameter count controlled.
        </p>
      </section>

      <section className="writeup-section">
        <h2>Loss and Diagnostics</h2>
        <p>
          The training objective combines field-level mean squared error with a small enstrophy penalty:
        </p>
        <p className="math-block">{String.raw`\[
          \mathcal{L}(\theta)
          =
          \left\|
            \mathcal{G}_{\theta}(a_i) - \omega_i(T)
          \right\|_2^2
          +
          \lambda
          \left(
            E[\mathcal{G}_{\theta}(a_i)] - E[\omega_i(T)]
          \right)^2,
          \qquad
          E[\omega] = \langle \omega^2 \rangle
        \]`}</p>
        <p>
          Here <span>{String.raw`\(E[\omega]=\langle \omega^2\rangle\)`}</span> is an enstrophy-like field statistic.
          The exported videos show the practical diagnostic loop: the numerical solver solution, the FNO finite time
          prediction, and the absolute error. The useful question is whether the FNO captures the advective transport and
          diffusive smoothing of the vorticity field better than a trivial initial-state baseline.
        </p>
      </section>

      <section className="writeup-section">
        <h2>Interpretation</h2>
        <p>
          This is a compact surrogate-model experiment. The FNO does not numerically integrate the Navier-Stokes equation
          step by step; it learns the finite-time solution operator from examples generated by the solver. That makes it
          useful for testing whether spectral neural operators can approximate flow evolution when the dominant dynamics
          are organized by coherent structures and low Fourier modes.
        </p>
      </section>
    </div>
  );
}

export default SpectralLearning;
